<?php

/**
 * @file
 * The primary PHP file for the Itchefer theme.
 */

/**
 * Implements hook_preprocess_input().
 *
 * Remove news-topic for everyone but administrators.
 */
function itchefer_preprocess_input(&$variables) {
  if ($variables['element']['#type'] === 'radio' && $variables['element']['#id'] === 'edit-field-topic-type-3') {
    if (!str_contains(implode($variables[user]->getRoles()), 'administrator')) {
      $variables['attributes']['disabled'] = TRUE;
    }
  }
}
